// AUTO-GENERATED by scripts/generate-calculator-index.ts — do not edit by hand.
// Run `npm run calculators:generate` after adding or removing a calculator folder.

import type { CalculatorContent, CalculatorDefinition, CalculatorMeta } from "./types";
import mortgageMeta from "./definitions/mortgage/meta";

export const calculatorMetas: readonly CalculatorMeta[] = [
  mortgageMeta,
];

/* eslint-disable @typescript-eslint/no-explicit-any */
export const contentLoaders: Record<string, () => Promise<{ default: CalculatorContent }>> = {
  "mortgage": () => import("./definitions/mortgage/content"),
};

export const definitionLoaders: Record<string, () => Promise<{ default: CalculatorDefinition<any> }>> = {
  "mortgage": () => import("./definitions/mortgage/definition"),
};
