// AUTO-GENERATED by scripts/generate-calculator-index.ts — do not edit by hand.
// Run `npm run calculators:generate` after adding or removing a calculator folder.

"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import { bindCalculator, CalculatorSkeleton, type BoundCalculatorProps } from "@/components/calculator/calculator-engine";

// One lazily-loaded chunk per calculator: a page only ships the math it needs.
// Keep each dynamic() call literal so Next.js can preload the chunk during SSR.
export const calculatorWidgets: Record<string, ComponentType<BoundCalculatorProps>> = {
  "mortgage": dynamic(() => import("./definitions/mortgage/definition").then((m) => bindCalculator(m.default)), { loading: CalculatorSkeleton }),
};
