/**
 * Generates the calculator registry from the folders in
 * src/calculators/definitions. Each folder is one calculator and must contain
 * meta.ts, definition.ts and content.ts.
 *
 *   npm run calculators:generate   # write the generated files
 *   npm run calculators:check      # fail if they are out of date (CI)
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const definitionsDir = path.join(root, "src/calculators/definitions");
const registryFile = path.join(root, "src/calculators/registry.generated.ts");
const widgetsFile = path.join(root, "src/calculators/widgets.generated.tsx");
const REQUIRED_FILES = ["meta.ts", "definition.ts", "content.ts"];
const HEADER = "// AUTO-GENERATED by scripts/generate-calculator-index.ts — do not edit by hand.\n// Run `npm run calculators:generate` after adding or removing a calculator folder.\n";

export function listCalculatorSlugs(): string[] {
  return readdirSync(definitionsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

function identifier(slug: string): string {
  return slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase()).replace(/^(\d)/, "_$1");
}

export function renderRegistry(slugs: string[]): string {
  const imports = slugs.map((slug) => `import ${identifier(slug)}Meta from "./definitions/${slug}/meta";`).join("\n");
  const metas = slugs.map((slug) => `  ${identifier(slug)}Meta,`).join("\n");
  const content = slugs.map((slug) => `  "${slug}": () => import("./definitions/${slug}/content"),`).join("\n");
  const definitions = slugs.map((slug) => `  "${slug}": () => import("./definitions/${slug}/definition"),`).join("\n");
  return `${HEADER}
import type { CalculatorContent, CalculatorDefinition, CalculatorMeta } from "./types";
${imports}

export const calculatorMetas: readonly CalculatorMeta[] = [
${metas}
];

/* eslint-disable @typescript-eslint/no-explicit-any */
export const contentLoaders: Record<string, () => Promise<{ default: CalculatorContent }>> = {
${content}
};

export const definitionLoaders: Record<string, () => Promise<{ default: CalculatorDefinition<any> }>> = {
${definitions}
};
`;
}

export function renderWidgets(slugs: string[]): string {
  const entries = slugs
    .map((slug) => `  "${slug}": dynamic(() => import("./definitions/${slug}/definition").then((m) => bindCalculator(m.default)), { loading: CalculatorSkeleton }),`)
    .join("\n");
  return `${HEADER}
"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import { bindCalculator, CalculatorSkeleton, type BoundCalculatorProps } from "@/components/calculator/calculator-engine";

// One lazily-loaded chunk per calculator: a page only ships the math it needs.
// Keep each dynamic() call literal so Next.js can preload the chunk during SSR.
export const calculatorWidgets: Record<string, ComponentType<BoundCalculatorProps>> = {
${entries}
};
`;
}

function main() {
  const slugs = listCalculatorSlugs();
  const problems: string[] = [];
  for (const slug of slugs) {
    if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug)) problems.push(`"${slug}" is not a valid kebab-case slug`);
    for (const file of REQUIRED_FILES) {
      if (!existsSync(path.join(definitionsDir, slug, file))) problems.push(`${slug}/${file} is missing`);
    }
  }
  if (problems.length) {
    console.error(`Calculator definitions are invalid:\n- ${problems.join("\n- ")}`);
    process.exit(1);
  }

  const outputs: [string, string][] = [
    [registryFile, renderRegistry(slugs)],
    [widgetsFile, renderWidgets(slugs)],
  ];

  if (process.argv.includes("--check")) {
    const stale = outputs.filter(([file, text]) => !existsSync(file) || readFileSync(file, "utf8") !== text);
    if (stale.length) {
      console.error(`Generated calculator index is out of date. Run \`npm run calculators:generate\`.`);
      process.exit(1);
    }
    console.log(`Calculator index is up to date (${slugs.length} calculators).`);
    return;
  }

  for (const [file, text] of outputs) writeFileSync(file, text);
  console.log(`Generated calculator index for ${slugs.length} calculators.`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) {
  main();
}
